force-app/main/default/objects/Expense_Request__c/Expense_Request__c.object-meta.xml
<CustomObject>
    <description>This object stores all expense request of users.</description>
    <label>Expense Request</label>
    <nameField>
        <displayFormat>ER-{0}</displayFormat>
        <label>Expense Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Request__c/fields/Approver_ID__c.field-meta.xml
<CustomField>
    <fullName>Approver_ID__c</fullName>
    <formula>CreatedBy.ManagerId</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Approver ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field stores status of each expense request. If the status is &quot;New&quot;, it means expense request is not submitted for approval and is open. If the status is &quot;Submitted&quot;, it means expense request is submitted for approval and is pending for approval from manager. If the status is &quot;Approved, it means the expense request is approved by manager. If the status is &quot;Rejected&quot;, it means the expense request is rejected by manager.</description>
    <inlineHelpText>This field stores status of each expense request. If the status is &quot;New&quot;, it means expense request is not submitted for approval and is open. If the status is &quot;Submitted&quot;, it means expense request is submitted for approval and is pending for approval from manager. If the status is &quot;Approved, it means the expense request is approved by manager. If the status is &quot;Rejected&quot;, it means the expense request is rejected by manager.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Expense_Request_Approved.cls
public with sharing class Expense_Request_Approved {
   
    @InvocableMethod(label='Approve the Expense Request' description='This accepts record id of a Expense Request and approve the expense request. And return result of the approval. ' category='Expense_Request__c')
    public static List<Results> approveExpenseRequest(List<Requests> rqs){

        String expId;
        Results rtn = new Results();
     
        try{

            for(Requests rq : rqs)
                expId = rq.expId;
           
            Expense_Request__c exp = [select id,Approver_ID__c from Expense_Request__c where id=:expId];
           
            if(UserInfo.getUserId()==exp.Approver_ID__c){
                changeExpenseStatus(expId, 'Approved');
                Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
                req.setComments('Request is approved');
                req.setAction('Approve');
                Id workItemId = getWorkItemId(expId); 
                req.setWorkitemId(workItemId);
                Approval.ProcessResult result =  Approval.process(req);
                rtn.result = 'success';
            }
            else 
                rtn.result = 'Failed, User is not authorised approver.';
        }
        catch(exception e){
            rtn.result = 'failed, error details: '+e;
        }
        return new List<Results>{rtn} ;
        
    }

    public class Requests {
        @InvocableVariable(label='Expense_Request__c RecordID' description='This is the recordID of Expense_Request__c record.' required=true)
        public String expId;
    }

    public class Results {
        @InvocableVariable(label='Status of approval' description='This contains result of approval. It includes, if approval was successful or a failure.' required=true)
        public String result;
    }

     /*
* This method will Approve the Expense
*/
@AuraEnabled
public static rtnResult approveRecord(id expId)    {
    
    rtnResult rtn = new rtnResult();
    
    try{
        changeExpenseStatus(expId, 'Approved');
        Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
        req.setComments('Request is approved');
        req.setAction('Approve');
        Id workItemId = getWorkItemId(expId); 
        req.setWorkitemId(workItemId);
        Approval.ProcessResult result =  Approval.process(req);
        rtn.ifSuccess = true ; rtn.details = 'success';
    }
    catch(exception e){
        rtn.ifSuccess = false ; rtn.details = e+'';
    }
    return rtn ;
    
}

    /*
* This method return workItemID
*/
public static Id getWorkItemId(Id targetObjectId) {
        
    Id retVal = null;
    for(ProcessInstanceWorkitem workItem  : [Select p.Id from ProcessInstanceWorkitem p where p.ProcessInstance.TargetObjectId =: targetObjectId])
        retVal  =  workItem.Id;
    return retVal;
}

/*
* To change the expense status
*/
public static void changeExpenseStatus(id expId, string status){
    Expense_Request__c exp = new Expense_Request__c();
    exp.id = expId;
    exp.status__c = status;
    update exp;
}

public class rtnResult{
    @AuraEnabled public Boolean ifSuccess;
    @AuraEnabled public String details ;
}
}